### ISSUE TITLE
Not a depending class is loaded.

### ISSUE THREAD

**Issue by FPSUsername** [Spliterash/MusicBox#1]
On server startup, I receive this warning.
Latest at the time Paper 1.16.4 server
NoteblockAPI development build (the latest release give the same error).

```
[12:49:25 WARN]: [MusicBox] Loaded class com.xxmicloxx.NoteBlockAPI.songplayer.PositionSongPlayer from NoteBlockAPI v1.6.1.1-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
```

This warning can also be related to a same type of warning with [Vault issue 789](https://github.com/MilkBowl/Vault/issues/789).
In that case, it's understandable.

**Comment by koca2000** [comment]
Can be fixed by changing 

https://github.com/Spliterash/MusicBox/blob/2a403d55f6b7b9b0df9f51c5986b0551cea50fed/src/main/resources/plugin.yml#L5

to `depend:`.

It may also solve #4.

**Comment by FPSUsername** [comment]
Correct, see [Optional Attributes](https://www.spigotmc.org/wiki/plugin-yml/#optional-attributes) of the `Plugin.yml` file.

**Comment by mibby** [comment]
@koca2000 Adding NoteBlockAPI as a dependency to Musicbox would fix the sync task call error with #4?

**Comment by koca2000** [comment]
@mibby I think it would because it looks like NoteBlockAPI is already disabled when MusicBox calls `SongPlayer.destroy()`.

**Comment by Spliterash** [comment]
Finnaly fix this
