### ISSUE TITLE
[Bug] Impulse at song ending not working (1.16.5)

### ISSUE THREAD

**Issue by joex92** [Spliterash/MusicBox#12]
when using the music sign, at the end of the song the impulse signal is not sending a redstone signal, it is triggering the lever, but it's not sending any redstone signal...

**Comment by joex92** [comment]
I suggest to change it a bit... because having to add a lever behind is a bit "bothersome", specially if you want to build something small or not too big... maybe add the possibility to just connect redstone behind it and that way send the ending song impulse directly to the redstone, instead of using a lever...

**Comment by Spliterash** [comment]
I cannot send a red signal from the void, these are not mods. I did it the way it was done in CraftBook. Even to be honest, I took the code from there

**Comment by joex92** [comment]
hmm, I know is not a mod, but aren't you sending it from the sign? 
but still, the lever is not sending any redstone signal... the lever is only being changed the state but not acting like it was activated...

**Comment by Spliterash** [comment]
What version you use, im check on 1.12.2 and all work

**Comment by joex92** [comment]
I'm on a paper fork 1.16.5... it's on the issue's title...

**Comment by Spliterash** [comment]
Oops, dont see, ok im check24 июн. 2021 г. 2:37 пользователь Joe X ***@***.***> написал:
I'm on a paper fork 1.16.5... it's on the issue's title...

**Comment by Spliterash** [comment]
Fixed in 2.0.5
It will be out tomorrow
