### ISSUE TITLE
[intended feature?] player speaker turned on when right-clicking a music sign (1.16.5)

### ISSUE THREAD

**Issue by joex92** [Spliterash/MusicBox#13]
everytime a music sign is set, when right-clicking it, the player gets its speaker turned on with the music sign's playlist/song...
It's a bit annoying because sometimes I just want to edit the music sign but instead it turns my player speaker on...
this happens only when the music sign has been set with a playlist/song....

**Comment by joex92** [comment]
I suggest changing it to edit the music sign or to open the timelapse inventory (instead of shift+right click)...

**Comment by joex92** [comment]
also, I only can open the timelapse menu doing [shift]+[right click] with **empty** hand, if I have any item in hand, it enables speaker mode (same as just right click)... and when this happens, the song is playing twice at the same time...

**Comment by Spliterash** [comment]
Fixed in 2.0.5
It will be out tomorrow
