### ISSUE TITLE
I can change distance heard for jukebox but sign doesn't change.

### ISSUE THREAD

**Issue by pupshadow** [Spliterash/MusicBox#14]
So you can change the distance for the jukebox with the config and it works great. 

For the sign however then you have the first line blank, and the second line is [music] ,  the third line is suppose to be the distance to hear the music , fourth line blank. 

my issue is the distance for the sign doesn't work properly it lets me change it but there is no actual change in distance at all its the same distance for default.

Is there a quick fix for this? if you need any more info please let me know.

My server version is git-Paper-775 (MC: 1.16.5) its most updated for 1.16.5

**Comment by Spliterash** [comment]
Fixed in 2.0.5
It will be out tomorrow
