### ISSUE TITLE
Musicbox2.0.4 1.17 Error No records visible

### ISSUE THREAD

**Issue by iLiDanMoon** [Spliterash/MusicBox#15]
Hello, I ran into such a problem, when I go to the records /musicbox menu, the records are not visible and an error appears in the console, but the records can be listened to in the shuffle mode

https://hastebin.com/cikebixeqa.md

https://imgur.com/a/C3lsnoD

Server Info: 

Core version 1.17 purpur #1255

Addon Plugins: 

NoteBlockAPI-1.6.1-SNAPSHOT

**Comment by Spliterash** [comment]
I haven't released the plugin for 1.17 yet

**Comment by Spliterash** [comment]
Fixed in 2.0.5
It will be out tomorrow
