### ISSUE TITLE
Обновление 1.18

### ISSUE THREAD

**Issue by div2005** [Spliterash/MusicBox#17]
Здравствуйте, уважаемый разработчик Илья! 
Уже 10 дней, как вышло обновление Майнкрафта 1.18. К большому сожалению, ваш NMS оказался устаревшим и плагин теперь не работает полноценно: GUI с пластинками не отображается, а музыка в жукбоксах ванильная. Хотелось бы узнать, когда нам стоит ожидать выхода новой версии, дабы мы могли и дальше наслаждаться прекрасной музыкой на нашем крутом сервере с помощью вашего плагина. 

В двух словах: а где :roflanBuldyga:

**Comment by Spliterash** [comment]
Спасибо за замечание уважаемый div2005, ваша просьба была исполнена.

**Comment by VitSun666** [comment]
Пасеба
