### ISSUE TITLE
Add midi support from NoteBlockAPI PR

### ISSUE THREAD

**Issue by mibby** [Spliterash/MusicBox#2]
Do you think it would be possible to branch MusicBox and add support for the upcoming midi support?
https://github.com/koca2000/NoteBlockAPI/pull/56

**Comment by Spliterash** [comment]
This thread is not yet merged with NoteBlockAPI. This is only possible if you compile this branch yourself. I am only for this opportunity, but until it appears in NoteBlockAPI, I can not do anything

**Comment by mibby** [comment]
Sure I suppose. I did compile the fork and it's likely the PR would be merged since the contributor has other PRs merged in the main branch. Just wanted to get a head start on the feature being readily available once merged.

**Comment by Spliterash** [comment]
"Как только, так сразу", or in English, as soon as there is a merger, I will immediately do

**Comment by mibby** [comment]
Wonderful. I'll be happy to help test when it happens.
