### ISSUE TITLE
suggest: Customize menu

### ISSUE THREAD

**Issue by Zarkness** [Spliterash/MusicBox#21]
My suggestion is to be able to customize all menus whether it be the position of items, add decorative elements like glass panels etc, add the ability to use custom minecraft-heads and use hex colors.

**Comment by Zarkness** [comment]
@Spliterash hello?

**Comment by Spliterash** [comment]
I'm not sure, because it will be difficult to implement.  It's one thing when it's a plugin with a static menu, it's another thing when every element here can change

**Comment by Spliterash** [comment]
Or leave example config and im take look

**Comment by Zarkness** [comment]
the only menu example I can think of is something like a menu plugin, something like this https://paste.helpch.at/wonunukaji.http

and about adding the ability to use rgb or hexadecimal colors is it possible to add it?
@Spliterash

**Comment by Zarkness** [comment]
I can think of a way that clearly each menu should have its own .yml or somehow you can make menus with menu creation plugins.

**Comment by Zarkness** [comment]
@Spliterash hello?

**Comment by Zarkness** [comment]
@Spliterash hello? 

> the only menu example I can think of is something like a menu plugin, something like this https://paste.helpch.at/henoqivaca.http
> 
> and about adding the ability to use rgb or hexadecimal colors is it possible to add it? @Spliterash

**Comment by Zarkness** [comment]
@Spliterash ⏫

**Comment by Spliterash** [comment]
Yes, it possible, but it not fast to implement. Also, I have no desire and time to develop this plugin yet, so do not rely on this feature in the near future
