### ISSUE TITLE
Обновление 1.18.2

### ISSUE THREAD

**Issue by VitSun666** [Spliterash/MusicBox#23]
Добрый день, после перехода на 1.18.2 пластинки перестали проигрываться в проигрывателях, а в меню генерироваться названия и описание пластинок.

**Comment by andryushka05** [comment]
> Добрый день, после перехода на 1.18.2 пластинки перестали проигрываться в проигрывателях, а в меню генерироваться названия и описание пластинок.

Решил проблему?

**Comment by Spliterash** [comment]
Обновил до 1.19
