### ISSUE TITLE
Music disc dupe

### ISSUE THREAD

**Issue by VitSun666** [Spliterash/MusicBox#9]
When a disc is loaded into jukebox from offhand, it remains in that hand and additional copy of disc is now playing in jukebox.
v2.0.3

**Comment by div2005** [comment]
https://www.youtube.com/watch?v=duF4TD5v038
Да, небольшая проблема и правда есть..

**Comment by div2005** [comment]
билд самому компилить? :D

**Comment by Spliterash** [comment]
Времени не было залить, так что можно сейчас вприципе
